Update function change station type with auto name offset
railmapgen/rmp pull request #276
Opened 2023-04-09 00:21 UTC by langonginc

修改单个函数，支持在修改车站类型的同时保持 `nameOffset*` 不变。

2023-04-09 04:59 UTC, thekingofcity commented
One more thing, the corresponding text should be updated. Something like nameOffsetX and nameOffsetY will be preserved if applicable.

https://github.com/railmapgen/rmp/blob/b3e0f25813be50b01784a69defd3cc4077def4bc/src/i18n/translations/en.json#L42
https://github.com/railmapgen/rmp/blob/b3e0f25813be50b01784a69defd3cc4077def4bc/src/i18n/translations/en.json#L323

2023-04-09 05:20 UTC, thekingofcity requested changes
Let's remove `//@ts-expect-error`

2023-04-09 05:20 UTC, thekingofcity commented on src/util/change-types.ts
> +    }
```suggestion
    const newAttrs = { ...stations[newStnType].defaultAttrs, names };
    if (
        !Object.values(StationsWithoutNameOffset).includes(currentStnType) ||
        !Object.values(StationsWithoutNameOffset).includes(newStnType)
    ) {
        (
            newAttrs as Exclude<
                ExternalStationAttributes[keyof ExternalStationAttributes],
                ShmetroBasic2020StationAttributes | undefined
            >
        ).nameOffsetX = graph.getNodeAttribute(
            selectedFirst,
            currentStnType as Exclude<StationType, StationType.ShmetroBasic2020>
        )!.nameOffsetX;
        (
            newAttrs as Exclude<
                ExternalStationAttributes[keyof ExternalStationAttributes],
                ShmetroBasic2020StationAttributes | undefined
            >
        ).nameOffsetY = graph.getNodeAttribute(
            selectedFirst,
            currentStnType as Exclude<StationType, StationType.ShmetroBasic2020>
        )!.nameOffsetY;
    }
```

2023-04-09 05:20 UTC, thekingofcity commented on src/util/change-types.ts
> +const AttrsInvalid = [StationType.ShmetroBasic2020];
```suggestion
const StationsWithoutNameOffset = [StationType.ShmetroBasic2020];
```

2023-04-09 07:56 UTC, langonginc reviewed
这样太好了～

2023-04-09 15:43 UTC, thekingofcity commented
诶这个你在本地能编译吗？没有缺import吗？

2023-04-10 15:35 UTC, langonginc commented
确实诶，您改完之后我没拉到本地试

2023-04-10 16:40 UTC, thekingofcity approved these changes
LGTM

2023-04-14 12:39 UTC, merged