#419 Add Change LineStyleType in Batch
railmapgen/rmp pull request #421
Opened 2023-08-23 11:03 UTC by langonginc

2023-08-25 04:01 UTC, thekingofcity requested changes
Some text and translations should be updated. Also, type casting is not need :)

2023-08-25 12:02 UTC, langonginc commented on src/i18n/translations/ja.json
> +                    "title": "일괄적으로 라인 유형 변경",
It's an accident 🌚

2023-08-25 12:03 UTC, langonginc commented
Thanks, I'll fix the translation.

2023-08-26 16:05 UTC, thekingofcity approved these changes
LGTM

2023-08-26 16:07 UTC, merged