#338 Enhance selection detail
railmapgen/rmp pull request #486
Opened 2023-11-12 23:04 UTC by langonginc

2023-11-13 07:42 UTC, thekingofcity requested changes

2023-11-13 07:42 UTC, thekingofcity commented on src/components/panels/details/info-section.tsx
> +        selected.forEach(node => {
This should be removed :)

2023-11-13 07:42 UTC, thekingofcity commented
Let's do another review after #484 is merged :)

2023-11-13 15:32 UTC, langonginc commented on src/components/panels/details/info-multiple-selection.tsx
> +                type: 'custom',
I just copied it from somewhere. I will try this tomorrow.

2023-11-13 15:37 UTC, langonginc commented on src/components/panels/details/info-multiple-selection.tsx
> +                type: 'custom',
I have a question that why we use .map rather than .forEach, or what's the difference between them. 🙃

2023-11-13 15:42 UTC, thekingofcity commented on src/components/panels/details/info-multiple-selection.tsx
> +                type: 'custom',
You won't get the returned value from forEach. It's basically a dead-end function call.

2023-11-14 14:26 UTC, langonginc commented on src/components/panels/details/info-multiple-selection.tsx
> +                type: 'custom',
Oh, I see. 😃

2023-11-19 08:14 UTC, thekingofcity commented on src/components/panels/details/info-multiple-selection.tsx
> +                {t('Selected Objects: ')} {selected.length}
Translation needed :)

2023-11-19 10:28 UTC, langonginc commented on src/components/panels/details/info-multiple-selection.tsx
> +                {t('Selected Objects: ')} {selected.length}
Added.

2023-11-19 10:39 UTC, thekingofcity approved these changes
LGTM

2023-11-22 12:35 UTC, merged